### ISSUE TITLE
IBM FHIR server search by Patient.meta.extensions fails despite proper configuration and rebuild from source 

### ISSUE THREAD

**Issue by jonathan-consensysHealth** [Equideum/FHIR#1]
The IBM FHIR server has the ability [as documented](https://ibm.github.io/FHIR/guides/FHIRSearchConfiguration) for configuring the search options and index using your own search code.  

I have been trying to configure the IBM FHIR server to search by Patient.meta.extension and despite my best effort have failed to even get their well documented example of Patient.extension.favorite-color example working. 

Pushing a SearchParameter resource to [base]/searchParameter fails to refresh the config.  Finally, I rebuilt from source after editing the ./config/default/extension-search-parameters.json file and while that doesn't return any errors now as I can now search using 'favorite-color' code, it fails to return any resources with this extended object.  

I am going to submit an issue to the origin issue, but this might need to be fix as a fork from their repo.

**Comment by jonathan-consensysHealth** [comment]
Confirmed as a bug and not resolved after re-compile of IBM FHIR server from source, which took > 2 hours and 1.7Gb.  Definitely will need to fork and re-write the java handler of extension-searchParameters.json

**Comment by jonathan-consensysHealth** [comment]
Here is the example FHIR SearchParameter resource that can either be POST to the `https://localhost:9443/fhir-server/api/v4/SearchParameter` endpoint and can even be queried using `https://localhost:9443/fhir-server/api/v4/SearchParameter\?code\=color` but apparently it doesn't trigger a re-index and make it searchable.  I tried manually adding it to the config on build and that didn't work either.  


```
{
    "resourceType": "SearchParameter",
    "id": "Patient-favorite-color",
    "url": "http://ibm.com/fhir/SearchParameter/Patient-favorite-color",
    "version": "4.0.0",
    "name": "color",
    "status": "draft",
    "experimental": false,
    "date": "2018-12-27T22:37:54+11:00",
    "publisher": "IBM FHIR Server Test",
    "contact": [{
            "telecom": [{
                    "system": "url",
                    "value": "http://ibm.com/fhir"
            }]
    },
    {
            "telecom": [{
                    "system": "url",
                    "value": "http://ibm.com/fhir"
            }]
    }],
    "description": "the patient's favorite color",
    "code": "color",
    "base": ["Patient"],
    "type": "string",
    "xpathUsage": "normal",
    "xpath": "f:Patient/f:extension[@url='http://ibm.com/fhir/extension/Patient/favorite-color']/f:valueString",
    "expression": "Patient.extension.where(url='http://ibm.com/fhir/extension/Patient/favorite-color').valueString",
    "multipleOr": true,
    "multipleAnd": true,
    "modifier": []
}

```

**Comment by jonathan-consensysHealth** [comment]
So, apparently POSTing to [base]/SearchParameter on IBM's FHIR server doesn't do what I thought it did (i.e. nothing).  I was expecting it to create a new index on that code. But this doesn't seem to be supported by IBM FHIR server.   Discussion regarding this `bug` can be found [here](https://github.com/IBM/FHIR/issues/2156).  This appears to be a `feature` and not a bug as it is computationally intensive to create new indexes on the fly and could take days to complete for FHIR servers with large amount of servers.  Therefore it seems that it needs to be configured then compiled or possibly a way to push the configuration to the docker image and used at run time.   Of note, the FHIR-registry approach doesn't yet seem to be enabled, so adding to the extensions-search.json file doesn't actually do anything.  I haven't yet tried creating a new tenant to see if the new tenant picks up the modified search by extension file.

**Comment by gmchad** [comment]
Configuration references can be read [here](https://github.com/ConsensysHealth/FHIR/blob/main/fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java) and updated [here](https://github.com/ConsensysHealth/FHIR/tree/main/fhir-server/liberty-config/config/default).

**Comment by gmchad** [comment]
Here is the example branch that shows the default tenant solution: https://github.com/ConsensysHealth/FHIR/tree/extension_example

Note:

- The **format** of the `extension-search-parameters.json` file

- the **location** of the file: `fhir-server/liberty-config/config/default/extension-search-parameters.json`

- sample query: `curl -k -u 'fhiruser:change-password' 'https://localhost:9443/fhir-server/api/v4/Patient?favorite-color=pink' | jq`
